### ISSUE TITLE
'module is not defined' on Windows

### ISSUE THREAD

**Issue by meetar** [tangrams/react-webpack-tangram-boilerplate#2]
On Windows 10 using git bash: following the instructions in the readme, everything appears to install and build correctly, and the server starts. However when loading http://localhost:8080 in chrome, FF, and IE, the page is blank (apart from Leaflet components) and the console shows:

```
blob:http://localhost:8080/583f718a-2912-4321-8c39-b440e42f43ec:1 Uncaught ReferenceError: module is not defined
```

The same procedure shows a map on Mac OS.

**Comment by ruatara** [comment]
@meetar did you manage to figure this out?

**Comment by meetar** [comment]
@ruatara No, I haven't looked at it recently.

**Comment by sk1me** [comment]
@ruatara @meetar Anyone have a solution or still nothing?

**Comment by meetar** [comment]
I still don't know why it's happening, but I discovered that I can fix it after the bundle has been generated by adding a line of code.

In the bundle.js, there's a block of code after a comment heading `/* 419 */` with this in the middle of it (you should be able to search for this):

    {module.exports=f()}

...for me it's at line 46292. If I modify that block so that it reads:

    {module = typeof module === 'undefined' ? {} : module; module.exports=f()}

... it works for me. As far as I can tell it has something to do with webpack, web workers, and windows.  ¯\\\_(ツ)\_/¯

**Comment by sk1me** [comment]
Hey, in webpack.config.js I have added second path to noParse and it seems to resolve the error:
`noParse: [/tangram\/dist\/tangram/, /tangram\\dist\\tangram/]`

**Comment by meetar** [comment]
Nice catch! I thought I'd already done that, because I did it in the other
webpack boilerplate demo. 😅 I've updated the repo here:
https://github.com/tangrams/react-webpack-tangram-boilerplate/commit/7a39f5baa6a48613cc2d456fb4ce8536a173484c
